[package]
name = "mfutures"
version = "0.1.0"
authors = ["harryk <kituyiharry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.19", default-features = true }
